version: '3'

services:
  terragrunt:
    image: alpine/terragrunt:1.3.9
    command: bash -c "terragrunt $COMMAND --terragrunt-exclude-dir ./"
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      TERRAGRUNT_PARALLELISM: 16 # * Max parallel builds
      TF_INPUT: false # * Disable interactive prompts
    volumes:
      - $DIR:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
